### PR TITLE
Grammar Interface, implementation & test class added

### PR DESCRIPTION
**Pull request by adeelahuma**

### CODE REVIEW

**Comment by gregwk** [comment]
Adeela,

This is looking good. Here are some comments:

(1) Change class name AdventureGameGrammar to GameGrammar. Likewise, change AdventureGameGrammarTest to GameGrammarTest.
(2) Change method name addAction to addGameAction
(3) In GameAction class, change method "setPatterns" to "addPattern" and make it so that it only takes one pattern (String)
(4) In GameAction class, get rid of "equals" and "hashCode" method. We can check equality with the identifier
(5) Create constructor GameAction(String id) and get rid of "setId()" method. This will force clients to set the id once and never change it.
(6) Add method "public boolean contains(String id)" to Grammar, so that clients can check if an identifier is already in there.
(7) Throw an illegal argument exception in the following cases: client tries to add identifier (to Grammar) that already exists; client tries to add empty string for an identifier or pattern; client tries to add null for identifier or pattern.
(8) Put the test class in "test/adventure" folder instead of "test/src/adventure"
(9) Make sure your tests pass (I have not looked at the test class in detail)

Cheers,
Dr. K

**Comment by gregwk** [comment]
Clean up the GameGrammer implementation a bit:

(1) Rename "grammar" to something less confusing, like "actionMap". The "grammar" is our abstraction, the "map" is part of our representation. 

(2) "contains" should be implemented as:

return actionMap.containsKey(actionId);

- passing in null, will make the method return false, which is correct
- actionMap is never null because you (as implementer) never make it null
- if actionMap is empty, the method returns false, which is correct

(3) "getGameAction" can be similarly simplified, but you do need:

if (!contains(actionId)) throw new IllegalArgumentException();

Dr. K

**Comment by adeelahuma** [comment]
Dr. K, 
I have implemented all the changes that you have suggested.

**Comment by gregwk** [comment]
Thanks Adeela! Looks good.

Dr. K

**Pull request merged**
