### PR TITLE
TreeGameWorld

### PR DESCRIPTION
**Pull request by Yezeli**
New methods added in.

Thanks
Yeze

### CODE REVIEW

**Comment by gregwk** [comment]
Branch has conflicts. Please pull from main repo, resolve conflicts and then resend pull request.

Dr. K

**Comment by Yezeli** [comment]
Prof.K

I have resolved some of the conflicts, but for the rest, I managed to resolve, but still doesn't work. 
Can the conflicts resolved by you?

Thanks
Yeze

**Comment by Yezeli** [comment]
Prof.K

I have resolved some of the conflicts, but for the rest, I managed to
resolve, but still doesn't work.
Can the conflicts resolved by you?

Thanks
Yeze

**Comment by gregwk** [comment]
Thanks Yeze -- I will take care of things from here.

Cheers,
Dr. K

**Comment by Yezeli** [comment]
Thank you very much,  Prof.K.

Yeze

2016年8月8日 4:44 PM，"Gregory Kulczycki" <notifications@github.com>写道：

**Pull request merged**
