### PR TITLE
actions modified 

### PR DESCRIPTION
**Pull request by adeelahuma**
modified actions after Alex's changes

### CODE REVIEW

**Comment by gregwk** [comment]
Adeela, your current pull request has conflicts. Please pull from my repository, add/merge your changes and then resubmit the pull request.

**Comment by adeelahuma** [comment]
Dr.K , I am running into errors while trying to resolve it and still not successful. 
Only file i want to push  is DefaultAction.

https://github.com/adeelahuma/AdventureFramework/blob/master/src/adventure/DefaultAction.java

How can i merge only this file?

**Comment by gregwk** [comment]
Instead of pulling, I replaced files locally, except for (1) the XML file (should not be here anyway), (2) Room.java, and (3) GameWorld.java. Closing this request now.

**Comment by adeelahuma** [comment]
okay Dr. K. I took Room and GameWorld from Alex's branch, so we should be
good.
Thanks,

**Pull request closed without merging**
